# Generated by Django 6.0.2 on 2026-02-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_tags_product_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(help_text='Теги через запятую', max_length=500, verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
