# Generated by Django 6.0.2 on 2026-02-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_product_category_alter_product_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dessert_type',
            field=models.CharField(choices=[('Торты', 'Торты'), ('Бенто', 'Бенто'), ('Горячий шоколад', 'Горячий шоколад'), ('Домашний зефир', 'Домашний зефир'), ('Маршмеллоу', 'Маршмеллоу'), ('Безе', 'Безе')], default='Торты', max_length=50, verbose_name='Тип десерта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Теги через запятую', max_length=500, verbose_name='Теги'),
        ),
    ]
