# Generated by Django 6.0.2 on 2026-02-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_product_tags_product_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.TextField(blank=True, verbose_name='Аллергены'),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, verbose_name='Состав'),
        ),
    ]
